-- -- Enable the uuid-ossp extension (if not already enabled)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
--
-- -- Create the users table
-- CREATE TABLE users (
--     id UUID PRIMARY KEY,
--     login VARCHAR(50) NOT NULL UNIQUE,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     password VARCHAR(100) NOT NULL,
--     role VARCHAR(50) NOT NULL
-- );
--
-- -- Insert initial data into users table
-- INSERT INTO users (id, login, email, password, role) VALUES
--     ('$2a$10$E1NRXjKZxZ1G0E/wMnYF1OIJ8O/2Ft2q3YBQqvJ86Gv8GHd06LQsq' ,'john_doe', 'john@example.com', '$2a$10$E1NRXjKZxZ1G0E/wMnYF1OIJ8O/2Ft2q3YBQqvJ86Gv8GHd06LQsq', 'ROLE_USER');